### Build settings ###

theme: jekyll-theme-midnight
plugins:
  - github-pages
  - jekyll-admin


### Site metadata ###

title: Coding Blog

# Internal links must be made relative to this to this path for Github Pages compatibility. Usually
# the name of the repo.
baseurl: "/coding-blog"
url: ""

short_date: "%b %-d, %Y"


### Tracking ###

google_analytics: UA-87705880-4
