### Build settings ###

markdown: kramdown
theme: jekyll-theme-midnight


### Site metadata ###

title: Coding Blog

# Internal links must be made relative to this to this path for Github Pages compatibility. Usually
# the name of the repo.
baseurl: "/coding-blog"
url: ""

short_date: "%b %-d, %Y"


### Content settings ###

collections:
  coding_blog:
    output: true

defaults:
  - scope:
      path: ""
      type: "coding_blog"
    values:
      layout: "default"
