# TODO: Replace and resolve comments here then switch to GUI editor in admin (comments will be lost). Remember server had to be restarted to get config changes.
# TODO: Configure admin to no pick up static fonts.

theme: jekyll-theme-midnight
plugins:
  - github-pages
  - jekyll-admin

exclude:
  - vendor/
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock

title: Coding Blog
baseurl: "/coding-blog"
url: https://michaelcurrin.github.io/coding-blog/
repository: MichaelCurrin/coding-blog

short_date: "%b %-d, %Y"

google_analytics: UA-87705880-4
