# TODO: Configure admin to not pick up static fonts.

title: Coding Blog
url: https://michaelcurrin.github.io
baseurl: /coding-blog

theme: jekyll-theme-midnight
plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-admin

exclude:
  - vendor/
  - LICENSE
  - Makefile
  - README.md
  - Gemfile
  - Gemfile.lock

short_date: "%b %-d, %Y"

google_analytics: UA-87705880-4
