### Site metadata ###

title: Coding Blog
description: "My blog of experiences and advice around coding"

### Build settings ###

url: https://michaelcurrin.github.io
baseurl: /coding-blog
repository: michaelcurrin/coding-blog

theme: jekyll-theme-midnight

short_date: "%b %-d, %Y"

google_analytics: UA-87705880-4

# TODO: Configure admin to not pick up static fonts.
# ...

defaults:
  - scope:
      path: ""
    values:
      layout: "page"

exclude:
  - vendor/
  - LICENSE
  - Makefile
  - README.md
  - Gemfile
  - Gemfile.lock
